version: "3"

name: react-native-android
services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    # extra_hosts:
      # - "host.docker.internal:host-gateway"
    
    command: tail -F anything #npm start
